export const DEFAULT_WORKFLOW_LANGUAGE = "English";
export const DEFAULT_WORKFLOW_PRACTICE = "General Construction";
export const DEFAULT_WORKFLOW_JURISDICTION = "General";

export const WORKFLOW_LANGUAGE_OPTIONS = [
  "English",
  "Chinese",
  "Spanish",
  "French",
  "German",
  "Japanese",
  "Korean",
  "Portuguese",
  "Italian",
  "Dutch",
  "Arabic",
  "Hebrew",
  "Persian",
  "Urdu",
  "Hindi",
  "Bengali",
  "Tamil",
  "Telugu",
  "Indonesian",
  "Malay",
  "Filipino",
  "Vietnamese",
  "Thai",
  "Burmese",
  "Khmer",
  "Lao",
  "Russian",
  "Ukrainian",
  "Turkish",
  "Polish",
  "Czech",
  "Romanian",
  "Greek",
  "Danish",
  "Finnish",
  "Norwegian",
  "Swedish",
  "Afrikaans",
  "Swahili",
  "Other",
] as const;

export const WORKFLOW_PRACTICE_OPTIONS = [
  "General Construction",
  "Carpentry",
  "Electrical",
  "Plumbing",
  "HVAC",
  "Roofing",
  "Concrete and Masonry",
  "Drywall and Painting",
  "Flooring",
  "Landscaping",
  "Remodeling",
  "Demolition",
  "Other",
] as const;

export const WORKFLOW_JURISDICTION_OPTIONS = [
  "General",
  "United States",
  "England and Wales",
  "European Union",
  "Singapore",
  "Hong Kong",
  "Australia",
  "Canada",
  "India",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Thailand",
  "Vietnam",
  "Japan",
  "South Korea",
  "China",
  "Taiwan",
  "Germany",
  "France",
  "Netherlands",
  "Ireland",
  "Scotland",
  "Luxembourg",
  "Switzerland",
  "Cayman Islands",
  "British Virgin Islands",
  "United Arab Emirates",
  "Saudi Arabia",
  "Brazil",
  "Mexico",
  "Other",
] as const;
